export const ADDCART_REQUESTING ='ADDCART_REQUESTING';
export const ADDCART_REQUESTED ='ADDCART_REQUESTED';
export const ADDCART_REQUESTERROR ='ADDCART_REQUESTERROR';

export const COMMENT_REQUESTING ='COMMENT_REQUESTING';
export const COMMENT_REQUESTED ='COMMENT_REQUESTED';
export const COMMENT_REQUESTERROR ='COMMENT_REQUESTERROR';