export const ADDCART_REQUESTING ='ADDCART_REQUESTING';
export const ADDCART_REQUESTED ='ADDCART_REQUESTED';
export const ADDCART_REQUESTERROR ='ADDCART_REQUESTERROR';

export const COMMENT_REQUESTING ='COMMENT_REQUESTING';
export const COMMENT_REQUESTED ='COMMENT_REQUESTED';
export const COMMENT_REQUESTERROR ='COMMENT_REQUESTERROR';

export const DETAILS_REQUESTING ='DETAILS_REQUESTING';
export const DETAILS_REQUESTED ='DETAILS_REQUESTED';
export const DETAILS_REQUESTERROR ='DETAILS_REQUESTERROR';