export const GETORDER_REQUESTING ='GETORDER_REQUESTING';
export const GETORDER_REQUESTED ='GETORDER_REQUESTED';
export const GETORDER_REQUESTERROR ='GETORDER_REQUESTERROR';

export const DELORDER_REQUESTING ='DELORDER_REQUESTING';
export const DELORDER_REQUESTED ='DELORDER_REQUESTED';
export const DELORDER_REQUESTERROR ='DELORDER_REQUESTERROR';