export const CART_REQUESTING ='CART_REQUESTING';
export const CART_REQUESTED ='CART_REQUESTED';
export const CART_REQUESTERROR ='CART_REQUESTERROR';


export const DEL_REQUESTING ='DEL_REQUESTING';
export const DEL_REQUESTED ='DEL_REQUESTED';
export const DEL_REQUESTERROR ='DEL_REQUESTERROR';
