export const PAY_REQUESTING ='PAY_REQUESTING';
export const PAY_REQUESTED ='PAY_REQUESTED';
export const PAY_REQUESTERROR ='PAY_REQUESTERROR';


export const PAYED_REQUESTING ='PAYED_REQUESTING';
export const PAYED_REQUESTED ='PAYED_REQUESTED';
export const PAYED_REQUESTERROR ='PAYED_REQUESTERROR';